# Generated by Django 5.0.8 on 2024-08-20 10:43

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bemor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, null=True, verbose_name='Telegram username')),
                ('fullname',
                 models.CharField(blank=True, max_length=255, null=True, verbose_name='Familiya Ism Sharif')),
                ('phone', models.CharField(blank=True, max_length=150, null=True, verbose_name='Telefon raqam')),
                ('telegram_id', models.IntegerField(blank=True, null=True, verbose_name='Telegram ID')),
                ('test_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Test turi')),
                ('file_id', models.CharField(max_length=150, null=True, verbose_name='Photo ID')),
            ],
            options={
                'verbose_name': "Bemorlar bo'limi",
                'verbose_name_plural': "Bemorlar bo'limi",
            },
        ),
    ]
