# Generated by Django 5.1b1 on 2024-06-30 17:18

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table1',
            fields=[
                ('lesson_number',
                 models.IntegerField(primary_key=True, serialize=False, verbose_name='Dars tartib raqami')),
                ('audio_id', models.CharField(max_length=150, null=True, verbose_name='Audio ID')),
                ('photo_id', models.CharField(max_length=150, null=True, verbose_name='Rasm ID')),
                ('video_id', models.CharField(max_length=150, null=True, verbose_name='Video ID')),
                ('document_id', models.CharField(max_length=150, null=True, verbose_name='Document ID')),
                ('file_name', models.CharField(max_length=150, null=True, verbose_name='Fayl nomi')),
                ('caption', models.TextField(max_length=4000, null=True, verbose_name='Tavsif')),
            ],
            options={
                'verbose_name': 'Psixoterapiya va psixologiya asoslari',
                'verbose_name_plural': 'Psixoterapiya va psixologiya asoslari',
            },
        ),
        migrations.CreateModel(
            name='Table2',
            fields=[
                ('lesson_number',
                 models.IntegerField(primary_key=True, serialize=False, verbose_name='Dars tartib raqami')),
                ('audio_id', models.CharField(max_length=150, null=True, verbose_name='Audio ID')),
                ('photo_id', models.CharField(max_length=150, null=True, verbose_name='Rasm ID')),
                ('video_id', models.CharField(max_length=150, null=True, verbose_name='Video ID')),
                ('document_id', models.CharField(max_length=150, null=True, verbose_name='Document ID')),
                ('file_name', models.CharField(max_length=150, null=True, verbose_name='Fayl nomi')),
                ('caption', models.TextField(max_length=4000, null=True, verbose_name='Tavsif')),
            ],
            options={
                'verbose_name': 'Tabobat va tibbiyotda mijoz va tepmerament ilmi',
                'verbose_name_plural': 'Tabobat va tibbiyotda mijoz va tepmerament ilmi',
            },
        ),
        migrations.CreateModel(
            name='Table3',
            fields=[
                ('lesson_number',
                 models.IntegerField(primary_key=True, serialize=False, verbose_name='Dars tartib raqami')),
                ('audio_id', models.CharField(max_length=150, null=True, verbose_name='Audio ID')),
                ('photo_id', models.CharField(max_length=150, null=True, verbose_name='Rasm ID')),
                ('video_id', models.CharField(max_length=150, null=True, verbose_name='Video ID')),
                ('document_id', models.CharField(max_length=150, null=True, verbose_name='Document ID')),
                ('file_name', models.CharField(max_length=150, null=True, verbose_name='Fayl nomi')),
                ('caption', models.TextField(max_length=4000, null=True, verbose_name='Tavsif')),
            ],
            options={
                'verbose_name': 'Miyaning neyroplastikligi va neyrobika',
                'verbose_name_plural': 'Miyaning neyroplastikligi va neyrobika',
            },
        ),
        migrations.CreateModel(
            name='Table4',
            fields=[
                ('lesson_number',
                 models.IntegerField(primary_key=True, serialize=False, verbose_name='Dars tartib raqami')),
                ('audio_id', models.CharField(max_length=150, null=True, verbose_name='Audio ID')),
                ('photo_id', models.CharField(max_length=150, null=True, verbose_name='Rasm ID')),
                ('video_id', models.CharField(max_length=150, null=True, verbose_name='Video ID')),
                ('document_id', models.CharField(max_length=150, null=True, verbose_name='Document ID')),
                ('file_name', models.CharField(max_length=150, null=True, verbose_name='Fayl nomi')),
                ('caption', models.TextField(max_length=4000, null=True, verbose_name='Tavsif')),
            ],
            options={
                'verbose_name': "Ta'lim va ruhiyat",
                'verbose_name_plural': "Ta'lim va ruhiyat",
            },
        ),
        migrations.CreateModel(
            name='Table5',
            fields=[
                ('lesson_number',
                 models.IntegerField(primary_key=True, serialize=False, verbose_name='Dars tartib raqami')),
                ('audio_id', models.CharField(max_length=150, null=True, verbose_name='Audio ID')),
                ('photo_id', models.CharField(max_length=150, null=True, verbose_name='Rasm ID')),
                ('video_id', models.CharField(max_length=150, null=True, verbose_name='Video ID')),
                ('document_id', models.CharField(max_length=150, null=True, verbose_name='Document ID')),
                ('file_name', models.CharField(max_length=150, null=True, verbose_name='Fayl nomi')),
                ('caption', models.TextField(max_length=4000, null=True, verbose_name='Tavsif')),
            ],
            options={
                'verbose_name': 'Farzandim va jigarbandim',
                'verbose_name_plural': 'Farzandim va jigarbandim',
            },
        ),
        migrations.CreateModel(
            name='Table6',
            fields=[
                ('lesson_number',
                 models.IntegerField(primary_key=True, serialize=False, verbose_name='Dars tartib raqami')),
                ('audio_id', models.CharField(max_length=150, null=True, verbose_name='Audio ID')),
                ('photo_id', models.CharField(max_length=150, null=True, verbose_name='Rasm ID')),
                ('video_id', models.CharField(max_length=150, null=True, verbose_name='Video ID')),
                ('document_id', models.CharField(max_length=150, null=True, verbose_name='Document ID')),
                ('file_name', models.CharField(max_length=150, null=True, verbose_name='Fayl nomi')),
                ('caption', models.TextField(max_length=4000, null=True, verbose_name='Tavsif')),
            ],
            options={
                'verbose_name': 'Nafs diagnostikasi',
                'verbose_name_plural': 'Nafs diagnostikasi',
            },
        ),
        migrations.CreateModel(
            name='Table7',
            fields=[
                ('lesson_number',
                 models.IntegerField(primary_key=True, serialize=False, verbose_name='Dars tartib raqami')),
                ('audio_id', models.CharField(max_length=150, null=True, verbose_name='Audio ID')),
                ('photo_id', models.CharField(max_length=150, null=True, verbose_name='Rasm ID')),
                ('video_id', models.CharField(max_length=150, null=True, verbose_name='Video ID')),
                ('document_id', models.CharField(max_length=150, null=True, verbose_name='Document ID')),
                ('file_name', models.CharField(max_length=150, null=True, verbose_name='Fayl nomi')),
                ('caption', models.TextField(max_length=4000, null=True, verbose_name='Tavsif')),
            ],
            options={
                'verbose_name': 'Sharq psixologiyasi va psixoterapiya',
                'verbose_name_plural': 'Sharq psixologiyasi va psixoterapiya',
            },
        ),
        migrations.CreateModel(
            name='Table8',
            fields=[
                ('lesson_number',
                 models.IntegerField(primary_key=True, serialize=False, verbose_name='Dars tartib raqami')),
                ('audio_id', models.CharField(max_length=150, null=True, verbose_name='Audio ID')),
                ('photo_id', models.CharField(max_length=150, null=True, verbose_name='Rasm ID')),
                ('video_id', models.CharField(max_length=150, null=True, verbose_name='Video ID')),
                ('document_id', models.CharField(max_length=150, null=True, verbose_name='Document ID')),
                ('file_name', models.CharField(max_length=150, null=True, verbose_name='Fayl nomi')),
                ('caption', models.TextField(max_length=4000, null=True, verbose_name='Tavsif')),
            ],
            options={
                'verbose_name': 'Ruhiy salomatlik',
                'verbose_name_plural': 'Ruhiy salomatlik',
            },
        ),
    ]
