# Generated by Django 5.1b1 on 2024-06-30 18:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('kurslar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table1',
            name='audio_id',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Audio ID'),
        ),
        migrations.AlterField(
            model_name='table1',
            name='document_id',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Document ID'),
        ),
        migrations.AlterField(
            model_name='table1',
            name='photo_id',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Rasm ID'),
        ),
        migrations.AlterField(
            model_name='table1',
            name='video_id',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Video ID'),
        ),
        migrations.AlterField(
            model_name='table2',
            name='audio_id',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Audio ID'),
        ),
        migrations.AlterField(
            model_name='table2',
            name='document_id',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Document ID'),
        ),
        migrations.AlterField(
            model_name='table2',
            name='photo_id',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Rasm ID'),
        ),
        migrations.AlterField(
            model_name='table2',
            name='video_id',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Video ID'),
        ),
        migrations.AlterField(
            model_name='table3',
            name='audio_id',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Audio ID'),
        ),
        migrations.AlterField(
            model_name='table3',
            name='document_id',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Document ID'),
        ),
        migrations.AlterField(
            model_name='table3',
            name='photo_id',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Rasm ID'),
        ),
        migrations.AlterField(
            model_name='table3',
            name='video_id',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Video ID'),
        ),
        migrations.AlterField(
            model_name='table4',
            name='audio_id',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Audio ID'),
        ),
        migrations.AlterField(
            model_name='table4',
            name='document_id',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Document ID'),
        ),
        migrations.AlterField(
            model_name='table4',
            name='photo_id',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Rasm ID'),
        ),
        migrations.AlterField(
            model_name='table4',
            name='video_id',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Video ID'),
        ),
        migrations.AlterField(
            model_name='table5',
            name='audio_id',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Audio ID'),
        ),
        migrations.AlterField(
            model_name='table5',
            name='document_id',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Document ID'),
        ),
        migrations.AlterField(
            model_name='table5',
            name='photo_id',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Rasm ID'),
        ),
        migrations.AlterField(
            model_name='table5',
            name='video_id',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Video ID'),
        ),
        migrations.AlterField(
            model_name='table6',
            name='audio_id',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Audio ID'),
        ),
        migrations.AlterField(
            model_name='table6',
            name='document_id',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Document ID'),
        ),
        migrations.AlterField(
            model_name='table6',
            name='photo_id',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Rasm ID'),
        ),
        migrations.AlterField(
            model_name='table6',
            name='video_id',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Video ID'),
        ),
        migrations.AlterField(
            model_name='table7',
            name='audio_id',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Audio ID'),
        ),
        migrations.AlterField(
            model_name='table7',
            name='document_id',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Document ID'),
        ),
        migrations.AlterField(
            model_name='table7',
            name='photo_id',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Rasm ID'),
        ),
        migrations.AlterField(
            model_name='table7',
            name='video_id',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Video ID'),
        ),
        migrations.AlterField(
            model_name='table8',
            name='audio_id',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Audio ID'),
        ),
        migrations.AlterField(
            model_name='table8',
            name='document_id',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Document ID'),
        ),
        migrations.AlterField(
            model_name='table8',
            name='photo_id',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Rasm ID'),
        ),
        migrations.AlterField(
            model_name='table8',
            name='video_id',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Video ID'),
        ),
    ]
